
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USUARIO
 */
public class ConteoCadena extends javax.swing.JFrame {

    /**
     * Creates new form ConteoCadena
     */
    public ConteoCadena() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtCadena = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblVocales = new javax.swing.JLabel();
        lblNumP = new javax.swing.JLabel();
        lblCadMod = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitulo.setText("Conteo!!!");

        txtCadena.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Activar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel1.setText("Escribir una oracion:");

        lblVocales.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblVocales.setText("Numero de vocales A:          E:          I:          O:          U:          ");

        lblNumP.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblNumP.setText("Numero de Palabras: ");

        lblCadMod.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblCadMod.setText("Oracion Modificada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumP)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVocales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCadMod)
                            .addComponent(txtCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVocales)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(lblNumP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCadMod)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cadena = txtCadena.getText();
        this.ModificarCadena(cadena);
        this.contarVocales(cadena);
        this.numeroPalabras(cadena);
        
    }//GEN-LAST:event_jButton1ActionPerformed
 
    public void contarVocales (String cadena){
        int contA = 0;
        int contE = 0;
        int contI = 0;
        int contO = 0;
        int contU = 0;
        
        //Funcion para contar el numero de vocales en una cadena
        for (int i = 0; i < cadena.length(); i++) {
            // Convierte a minúscula para hacer comparaciones sin distinción de mayúsculas o minúsculas
            char caracterActual = Character.toLowerCase(cadena.charAt(i)); 
            switch (caracterActual) {
                case 'a' -> contA++;
                case 'e' -> contE++;
                case 'i' -> contI++;
                case 'o' -> contO++;
                case 'u' -> contU++;
                default -> {
                }
            }
        }
        
        lblVocales.setText("Numero de vocales  A: "+contA+"   E:"+contE+"   I:"+contI+"   O:"+contO+"   U:"+contU);        
    }
    
    public void numeroPalabras (String cadena){
        int cont = 0;
         //Funcion para subdividir una cadena cada que hay un esopacio y contar el numero de palabras
        String[] partes = cadena.split(" ");

        // Iterar sobre las partes e imprimir cada fragmento
        for (String parte : partes) {
            JOptionPane.showMessageDialog(null, "las palabras de la oracion son: "+parte);
            cont++;
        }
        lblNumP.setText("Numero de Palabras: "+cont);
        
    }
    
    public void ModificarCadena (String cadena){
        String nueva = "";
       //Funcion para reemplazar en una cadena las A=@ y a las O=$
        for (int i = 0; i < cadena.length(); i++) {
            switch (cadena.charAt(i)) {
                case 'a' -> nueva += "@";
                case 'o' -> nueva += "$";
                default -> nueva += cadena.charAt(i); 
            }
        }
                
        lblCadMod.setText("Oracion Modificada: "+nueva);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConteoCadena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConteoCadena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConteoCadena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConteoCadena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConteoCadena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCadMod;
    private javax.swing.JLabel lblNumP;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVocales;
    private javax.swing.JTextField txtCadena;
    // End of variables declaration//GEN-END:variables
}
